[package]
name = "pkgconf"
version = "0.1.0"
edition = "2024"
description = "A Rust rewrite and drop-in replacement for pkg-config/pkgconf"
license = "ISC"
readme = "../../README.md"
repository = "https://github.com/noverby/pkg-config-rs"
keywords = ["pkg-config", "pkgconf", "build-tools"]
categories = ["command-line-utilities", "development-tools::build-utils"]

[[bin]]
name = "pkgconf"
path = "src/main.rs"

[dependencies]
libpkgconf = { path = "../libpkgconf" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
