[package]
name = "systemd-coredump"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[[bin]]
name = "systemd-coredump"
path = "src/main.rs"

[dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3"
