[package]
name = "systemctl"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[[bin]]
name = "systemctl"
path = "src/main.rs"

[dependencies]
libsystemd = { path = "../libsystemd" }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
