[package]
name = "systemd-creds"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[[bin]]
name = "systemd-creds"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"
aes-gcm = "0.10"
sha2 = "0.10"
base64 = "0.22"
