[package]
name = "systemd-logind"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[[bin]]
name = "systemd-logind"
path = "src/main.rs"

[dependencies]
libc = "0.2"
log = "0.4"
nix = { version = "0.31", features = [
  "signal",
  "process",
  "fs",
  "ioctl",
  "poll",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
