# Run `direnv reload` to apply changes to the repository.

[default.extend-words]
# Upstream API name from openssh-sftp-client crate
clonable = "clonable"

[default]
extend-ignore-re = [
  "Automattic",
  "Tre",
  "tre",
  "Importd",
  "Localed",
  "Iinclude",
  "localed",
  "OIF",
  "oif",
]

[files]
extend-exclude = [
  # Project is still in Danish
  "wiki/**",
  "config/secrets/*.age",
]
ignore-hidden = false
