# After editing config files in this directory, run `direnv reload` to apply changes to the repository.

[default]
extend-ignore-re = [
  "Automattic",
  "Tre",
  "tre",
  "Importd",
  "Localed",
  "Iinclude",
  "localed",
  "OIF",
  "oif"
]

[files]
extend-exclude = [
   # Project is still in Danish
  "wiki/**",
  "secrets/*.age"
]
ignore-hidden = false
