[package]
name = "coredumpctl"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[[bin]]
name = "coredumpctl"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"

[dev-dependencies]
tempfile = "3"
