[package]
name = "systemd-shutdown"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[[bin]]
name = "systemd-shutdown"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"
nix = { version = "0.31", features = ["mount", "reboot", "signal", "process", "fs"] }
log = "0.4"
