[default]
extend-ignore-re = [
  "Automattic",
  "Tre",
  "tre",
  "Importd",
  "Localed",
  "Iinclude"
]

[files]
extend-exclude = [
   # Project is still in Danish
  "wiki/**",
  "secrets/*.age"
]
ignore-hidden = false