[package]
name = "systemd-run"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[[bin]]
name = "systemd-run"
path = "src/main.rs"

[dependencies]
libsystemd = { path = "../libsystemd" }
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"
serde_json = "1.0"
