[package]
name = "systemd-mount"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[[bin]]
name = "systemd-mount"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
