# Run `direnv reload` to apply changes to the repository.
rules:
  description-empty:
    level: error
  description-format:
    level: error
    format: ^[A-Z].*$
  subject-empty:
    level: error
  type-empty:
    level: error
  type:
    level: error
    options:
      - feat
      - fix
      - chore
      - doc
  scope-empty:
    level: error
  scope:
    level: error
    optional: false
    options:
      - backend
      - homepage
      - config
      - nixos
      - home-manager
      - devenv
      - flake
      - nixos-rs
      - pkgs
      - pkg-config-rs
      - readme
      - slides
      - systemd-rs
      - tangled
      - wasm-mojo
      - wasmtime-mojo
      - zed-mojo
      - nu-plugin-tramp
      - wiki
