[package]
name = "systemd"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[[bin]]
name = "systemd"
path = "src/main.rs"

[dependencies]
libsystemd = { path = "../libsystemd" }
