[package]
name = "systemd-user-sessions"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[[bin]]
name = "systemd-user-sessions"
path = "src/main.rs"

[dependencies]

[dev-dependencies]
tempfile = "3"
