[package]
name = "libsystemd"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[dependencies]
signal-hook = "0.4"
libc = "0.2"
nix = { version = "0.31", features = ["user", "process", "mount", "poll", "fs", "signal", "socket", "event", "hostname"] }
log = "0.4"
fern = "0.7"
chrono = "0.4"
threadpool = "1.8"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1.10"
aes-gcm = "0.10"
sha2 = "0.10"
base64 = "0.22"

dbus = { version = "0.9", optional = true }
shlex = "1.3"
clap = { version = "4.5", features = ["derive"] }
shmemfdrs = "0.1"
which = "8.0"

[dev-dependencies]
tempfile = "3"

[features]
dbus_support = ["dbus"]
linux_eventfd = []
cgroups = []
