[package]
name = "systemd-ask-password"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[[bin]]
name = "systemd-ask-password"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"
uuid = { version = "1", features = ["v4"] }
